export {default as Header} from "./Header.vue"
export {default as Footer} from "./Footer.vue"
export {default as Sec1} from "./Sec1.vue"
export {default as Sec2} from "./Sec2.vue"
export {default as Sec3} from "./Sec3.vue"
export {default as Sec4} from "./Sec4.vue"
export {default as ImgWrapper} from "./ImgWrapper.vue"