# Generated by Django 3.2.6 on 2021-08-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Regular', 'Regular'), ('Large', 'Large')], max_length=30)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OtherMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='')),
                ('water_temperature', models.CharField(choices=[('Hot', 'Hot'), ('Ice', 'Ice'), ('Hot Only', 'Hot Only'), ('Ice Only', 'Ice Only')], max_length=10, null=True)),
                ('espresso', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], max_length=50, null=True)),
                ('soft_drink', models.BooleanField(default=False)),
                ('for_kids', models.BooleanField(default=False)),
            ],
        ),
    ]
