# Generated by Django 3.2.6 on 2021-08-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othermenu',
            old_name='for_kids',
            new_name='kids',
        ),
        migrations.RenameField(
            model_name='othermenu',
            old_name='soft_drink',
            new_name='softDrink',
        ),
        migrations.RenameField(
            model_name='othermenu',
            old_name='water_temperature',
            new_name='temperature',
        ),
    ]
