# Generated by Django 3.2.6 on 2021-08-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210809_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othermenu',
            old_name='kids',
            new_name='forKids',
        ),
        migrations.RemoveField(
            model_name='othermenu',
            name='picture',
        ),
        migrations.AddField(
            model_name='othermenu',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='othermenu',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Regular', 'Regular'), ('Large', 'Large')], max_length=30, null=True),
        ),
    ]
